### ISSUE TITLE
/hub doesn't work in some games

### ISSUE THREAD

**Issue by nomadjimbob** [STEMMechanics/STEMCraft-Core#3]
for example, in tntrun, using /hub does not teleport you back to the hub has tntrun takes over. The plugin needs to be updated to allow dynamic commands for /hub, for example, /hub would by default teleport the player to the hub world. In TNTRun, /hub would run `/tntrun leave`, same for bedwars, etc.

**Comment by ProjectHSI** [comment]
Fixed by https://github.com/STEMMechanics/STEMCraft/pull/5.
