### ISSUE TITLE
Documentation for the "Starlight" mod recommendation is inaccurate.

### ISSUE THREAD

**Issue by ProjectHSI** [STEMMechanics/STEMCraft-Core#30]
The *Starlight* mod description as present on https://www.stemcraft.com.au is inaccurate. Starlight is a lighting engine rewrite as opposed to a mod which optimizes chunk loading.

**Comment by nomadjimbob** [comment]
You should have access to edit pages on GitBook using your GitHub credentials

**Comment by ProjectHSI** [comment]
can you help me? i don't have access to a different org in gitbook other than the one created during signup

**Comment by ProjectHSI** [comment]
fixed in discord.
