### ISSUE TITLE
API Version Outdated

### ISSUE THREAD

**Issue by ProjectHSI** [STEMMechanics/STEMCraft-Core#35]
_api-version_ in _plugin.yml_ is set to target _1.19.x_ and _Spigot-API_ in _pom.xml_ is set to target _1.19.x_.

Since we're targeting _1.20.x_, I recommend we switch these two to target _1.20.x_.

**Comment by nomadjimbob** [comment]
Any chance you can PR that into the 1.1 release branch as a fix?

**Comment by ProjectHSI** [comment]
i'll put the branch under the """folder""" *hotfix*, but otherwise i'll PR this.

**Comment by ProjectHSI** [comment]
what was the mc version of the server?

**Comment by nomadjimbob** [comment]
It will be updated to latest today, but currently at git-Purpur-2082 (MC: 1.20.2)

**Comment by ProjectHSI** [comment]
Thanks. I just needed it so I know which Spigot-API build to update to.

**Comment by ProjectHSI** [comment]
I've just submitted the pull request.

**Comment by ProjectHSI** [comment]
https://github.com/STEMMechanics/STEMCraft-Core/pull/36
