### ISSUE TITLE
Hunger is reset in survival when you leave and rejoin

### ISSUE THREAD

**Issue by nomadjimbob** [STEMMechanics/STEMCraft-Core#50]
Reported by ProjectHSI

**Comment by ProjectHSI** [comment]
i think hunger and health are reset on join in STEMCraft and aren't set back to their previous values when joining the survival world.

**Comment by nomadjimbob** [comment]
It should be handled by the GameMode Inventory feature so I will need to see why it’s not being set correctly

**Comment by ProjectHSI** [comment]
Not sure if you know about this but your email client is appending the entire content of the email to be replied to with the reply email which causes some weird stuff to happen on the GitHub website.

**Comment by nomadjimbob** [comment]
fixed in 1.3.2
