### ISSUE TITLE
Move release notes to releases and not the README.

### ISSUE THREAD

**Issue by ProjectHSI** [STEMMechanics/STEMCraft-Core#65]
Old versions that don't have a release on GitHub can probably still be included but, why not keep the release notes in the releases instead? There's also a change log on the website.
\

**Comment by nomadjimbob** [comment]
Because most projects that I work on require it to be in the README and it has become habit for me to do.

> There's also a change log on the website.

Yes, I write it. The public wouldn't visit the GitHub page has I don't promote it heavily.

**Comment by ProjectHSI** [comment]
> Because most projects that I work on require it to be in the README

wdym require? do you mean they don't use releases?

> > There's also a change log on the website.
>
> Yes, I write it. The public wouldn't visit the GitHub page has I don't promote it heavily.

I'm not talking about the website being replaced. That can stay.

**Comment by nomadjimbob** [comment]
They don't use a RELEASES file. Releases/Tags are used to snapshot however. Most projects I work on, senior managers require all release notes, history, public documentation and details to be stored within a single description file in the project.

**Comment by ProjectHSI** [comment]
Ah, ok.

**Comment by ProjectHSI** [comment]
Changed the closure type to more accurately reflect the issue state.
