### ISSUE TITLE
SMWaystones.checkWaystoneExists appears to halt on waiting for the SQL DB

### ISSUE THREAD

**Issue by ProjectHSI** [STEMMechanics/STEMCraft-Core#72]

**Comment by nomadjimbob** [comment]
The issue appears to be with the SQLite engine and the query, not so much 'halting' but being stuck in some kind of query loop. Need to add in some SMDebugger.debug calls (printed when the debug flag `debug.SMWaystones` is set to true in config) to get what the final query is, and step the results to see what is happening

**Comment by ProjectHSI** [comment]
Could we push https://github.com/STEMMechanics/STEMCraft-Core/commit/ffb19cb1c01870f0d7d9269c19a2b427953b8a47 to the server?

**Comment by nomadjimbob** [comment]
I will need to do a full backup, start the server in maintenance mode and add this commit as it is based off main while the server is running on release/1.5

But this only times the query, we already know the query is running for at least 22 seconds with only 5 records in the database

**Comment by ProjectHSI** [comment]
added a new commit which names the sql query and uses SMDebugger

**Comment by ProjectHSI** [comment]
> I will need to do a full backup, start the server in maintenance mode and add this commit as it is based off main while the server is running on release/1.5
> 
> But this only times the query, we already know the query is running for at least 22 seconds with only 5 records in the database

the query is taking longer than that i think. in the spark timings it's showing the SQL query and in fact the underlying engine as severely hogging the server performance

**Comment by ProjectHSI** [comment]
https://github.com/STEMMechanics/STEMCraft-Core/tree/fix/checkWaystoneExistsDebug (branch i'm working things on), should be based off release/1.5
