### ISSUE TITLE
Specify /repair command in README.md change log?

### ISSUE THREAD

**Issue by ProjectHSI** [STEMMechanics/STEMCraft-Core#9]
The change log just specifies "Added /repair command", perhaps specify a little more in that change log?

**Comment by nomadjimbob** [comment]
It could have a summary of the command. A detailed description should be listed over the website, which I admit is way behind in updates.

Did you want to update the readme?

**Comment by ProjectHSI** [comment]
sorry for the late response.
just a summary is fine.
